// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddAnyFilePkgString = "0a9cb261-f413-4fbe-998e-a1e864394ff1";
        public static Guid guidAddAnyFilePkg = new Guid(guidAddAnyFilePkgString);

        public const string guidAddAnyFileCmdSetString = "6a2f7463-c7a4-418f-8ad8-db3de6105c42";
        public static Guid guidAddAnyFileCmdSet = new Guid(guidAddAnyFileCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}