// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    internal sealed partial class Vsix
    {
        public const string Id = "7bf9a1b6-a1b0-4cc6-acad-684e0553d01b";
        public const string Name = "Add New File Plus (64-bit) - Jude Edition";
        public const string Description = @"The fastest and easiest way to add new files to any project - including files that start with a dot";
        public const string Language = "en-US";
        public const string Version = "4.1.1";
        public const string Author = "Jude Vajira";
        public const string Tags = "file, add, template";
    }
}
